import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{CheckCircle2,Download,FileUp,History,LogOut,Search,Settings,ShieldCheck,Sparkles}from'lucide-react';
import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000';
let token=localStorage.token||'',role=localStorage.role||'viewer',currentEmail=localStorage.email||'';
const api=async(path:string,init:RequestInit={})=>{const r=await fetch(API+path,{...init,headers:{Authorization:`Bearer ${token}`,...(init.headers||{})}});if(!r.ok)throw Error((await r.json().catch(()=>({detail:'Request failed'}))).detail);return r.headers.get('content-type')?.includes('text/csv')?r.blob():r.json()};
function App(){
 const[logged,setLogged]=useState(!!token),[email,setEmail]=useState('reviewer@intain.demo'),[password,setPassword]=useState('Demo@123'),[notice,setNotice]=useState('');
 const[datasets,setDatasets]=useState<any[]>([]),[dataset,setDataset]=useState(''),[overview,setOverview]=useState<any>(),[profile,setProfile]=useState<any>(),[exceptions,setExceptions]=useState<any[]>([]),[verification,setVerification]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]);
 const[selected,setSelected]=useState<any>(),[history,setHistory]=useState<any>(),[correcting,setCorrecting]=useState(false),[value,setValue]=useState(''),[reason,setReason]=useState('Confirmed from source document'),[notes,setNotes]=useState('');
 const[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState(''),[severityFilter,setSeverityFilter]=useState(''),[uploading,setUploading]=useState(false),[adminOpen,setAdminOpen]=useState(false),[users,setUsers]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]);const fileInput=useRef<HTMLInputElement>(null);
 const load=async(id=dataset)=>{if(!id)return;try{const[o,p,e,v,a]=await Promise.all([api(`/datasets/${id}/overview`),api(`/datasets/${id}/profile`),api(`/datasets/${id}/exceptions`),api(`/datasets/${id}/verification`),api(`/datasets/${id}/audit`)]);setOverview(o);setProfile(p);setExceptions(e);setVerification(v);setAudit(a)}catch(e:any){setNotice(e.message)}};
 useEffect(()=>{if(logged)api('/datasets').then((x:any[])=>{setDatasets(x);if(x[0])setDataset(x[0].id)}).catch(()=>setLogged(false))},[logged]);useEffect(()=>{load()},[dataset]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)return setNotice(d.detail);token=d.access_token;role=d.user.role;currentEmail=d.user.email;localStorage.token=token;localStorage.role=role;localStorage.email=currentEmail;setNotice('');setLogged(true)};
 const upload=async(file?:File)=>{if(!file)return;setUploading(true);try{const form=new FormData();form.append('file',file);const d=await api('/datasets/upload',{method:'POST',body:form});setDatasets(x=>[d,...x]);setDataset(d.id);setNotice(`${file.name} uploaded: ${d.rows} records detected. Review the profile, then validate.`)}catch(e:any){setNotice(e.message)}finally{setUploading(false);if(fileInput.current)fileInput.current.value=''}};
 const demo=async()=>{try{const d=await api('/datasets/demo',{method:'POST'});setDatasets(x=>x.some(y=>y.id===d.id)?x:[d,...x]);setDataset(d.id);setNotice(d.reused?'Existing demo selected.':'Demo loaded. Run validation.')}catch(e:any){setNotice(e.message)}};
 const validate=async()=>{try{await api(`/datasets/${dataset}/normalize`,{method:'POST'});const r=await api(`/datasets/${dataset}/validate`,{method:'POST'});setNotice(`Validation completed: ${r.exceptions} issues found.`);load()}catch(e:any){setNotice(e.message)}};
 const loadAdmin=async()=>{try{const[u,r]=await Promise.all([api('/admin/users'),api('/admin/validation-rules')]);setUsers(u);setRules(r);setAdminOpen(true)}catch(e:any){setNotice(e.message)}};
 const updateRule=async(rule:any,value:string)=>{try{await api(`/admin/validation-rules/${rule.key}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({value:Number(value),enabled:rule.enabled})});setNotice(`${rule.label} updated.`);loadAdmin()}catch(e:any){setNotice(e.message)}};
 const assign=async(email:string)=>{try{await api(`/datasets/${dataset}/assign-reviewers`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify([email])});setNotice(`Dataset assigned to ${email}.`)}catch(e:any){setNotice(e.message)}};
 const openException=async(x:any)=>{setSelected(x);if(role==='reviewer')try{await api(`/exceptions/${x.id}/start-review`,{method:'POST'});load()}catch(e:any){setNotice(e.message)}};
 const assist=async()=>{try{const r=await api(`/exceptions/${selected.id}/ai`,{method:'POST'});setSelected({...selected,ai_explanation:r.explanation,ai_suggestion:r.suggestion})}catch(e:any){setNotice(e.message)}};
 const review=async(action:string)=>{try{const field=selected.field.split(',')[0].trim();const changes=action==='approve'?{[field]:value}:{};const r=await api(`/exceptions/${selected.id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,changes,reason,notes})});setCorrecting(false);setSelected(undefined);setNotice(action==='approve'?`Correction saved · Rule ${r.validation_result} · Record ${r.record_status}.`:'Finding rejected and audited.');load()}catch(e:any){setNotice(e.message)}};
 const openHistory=async(id:string)=>{try{setHistory(await api(`/loans/${id}/history`))}catch(e:any){setNotice(e.message)}};
 const download=(kind:string)=>api(`/datasets/${dataset}/export/${kind}`).then((b:Blob)=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${kind}.csv`;a.click();URL.revokeObjectURL(a.href)}).catch((e:any)=>setNotice(e.message));
 const filtered=useMemo(()=>verification.filter(v=>(!query||String(v.loan_id).toLowerCase().includes(query.toLowerCase()))&&(!statusFilter||v.status===statusFilter)&&(!severityFilter||v.severities.includes(severityFilter))),[verification,query,statusFilter,severityFilter]);
 if(!logged)return <Login email={email} password={password} notice={notice} setEmail={setEmail} setPassword={setPassword} submit={login}/>;
 return <main><header><div><ShieldCheck/><b>Intain</b><span>Loan Data Verification Copilot</span></div><span className="role-badge">{role.toUpperCase()}</span><button className="ghost" onClick={()=>{localStorage.clear();token='';setLogged(false)}}><LogOut size={16}/> Sign out</button></header>
 <aside>{role==='admin'&&<><input ref={fileInput} className="file-input" type="file" accept=".csv,.xlsx,.xls" onChange={e=>upload(e.target.files?.[0])}/><button disabled={uploading} onClick={()=>fileInput.current?.click()}><FileUp size={16}/> {uploading?'Uploading…':'Upload CSV / Excel'}</button><button className="ghost" onClick={demo}>Load Demo Dataset</button><button disabled={!dataset} onClick={validate}><ShieldCheck size={16}/> Normalize & Validate</button><button className="ghost" onClick={loadAdmin}><Settings size={16}/> Admin Console</button></>}<label>Dataset<select value={dataset} onChange={e=>setDataset(e.target.value)}><option value="">Select dataset</option>{datasets.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{dataset&&['verified','exceptions','audit'].map(k=><button className="ghost" onClick={()=>download(k)} key={k}><Download size={16}/> Export {k}</button>)}</aside>
 <section className="content">{notice&&<div className="notice">{notice}</div>}<h1>Operations dashboard</h1>{!dataset?<div className="empty">{role==='admin'?'Upload a CSV or Excel loan tape, or load the demo dataset.':'No assigned dataset is available.'}</div>:<><div className="cards"><Card title="Data quality score" value={`${overview?.quality_score??'—'}%`}/><Card title="Records" value={overview?.records??'—'}/><Card title="Open exceptions" value={Object.values(overview?.exceptions||{}).reduce((a:any,b:any)=>a+b,0)}/><Card title="Verified" value={`${overview?.verified??0}/${overview?.records??0}`}/></div><div className="grid"><Profile profile={profile}/><Queue overview={overview} exceptions={exceptions} open={openException}/></div><Verification rows={filtered} query={query} setQuery={setQuery} status={statusFilter} setStatus={setStatusFilter} severity={severityFilter} setSeverity={setSeverityFilter} history={openHistory}/><section className="panel audit"><h2>Audit history</h2>{audit.length?audit.slice(0,10).map(a=><p key={a.id}><b>{a.event}</b> · {a.actor} ({a.role||'system'})<br/><small>{String(a.created_at)} · Loan {a.loan_id||'dataset'}</small></p>):<p>No audit events yet.</p>}</section></>}</section>
 {selected&&<ExceptionDrawer item={selected} role={role} close={()=>setSelected(undefined)} assist={assist} correct={()=>{const field=selected.field.split(',')[0].trim();setValue(String(selected.record[field]??''));setCorrecting(true)}} reject={()=>review('reject')} history={()=>openHistory(selected.loan_id)}/>} {correcting&&<Correction item={selected} value={value} setValue={setValue} reason={reason} setReason={setReason} notes={notes} setNotes={setNotes} close={()=>setCorrecting(false)} save={()=>review('approve')}/>} {adminOpen&&<Admin users={users} rules={rules} dataset={dataset} close={()=>setAdminOpen(false)} updateRule={updateRule} assign={assign}/>} {history&&<HistoryModal data={history} close={()=>setHistory(undefined)}/>}</main>;
}
function Login(p:any){return <main className="login"><section className="login-card"><div className="login-form"><ShieldCheck size={44}/><p className="eyebrow">INTAIN FINTECH CHALLENGE 2026</p><h1>Loan Data Verification Copilot</h1><p>Turn messy loan data into verified, explainable, auditable records.</p><form onSubmit={p.submit}><input value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)}/><input type="password" value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)}/><button>Sign in</button></form><small>Admin: admin@intain.demo / Admin@123<br/>Reviewer: reviewer@intain.demo / Demo@123<br/>Viewer: viewer@intain.demo / Viewer@123</small>{p.notice&&<p className="err">{p.notice}</p>}</div><div className="login-story"><ShieldCheck size={56}/><h2>From messy loan tape to trusted data.</h2><p>Deterministic controls, human review, and traceable decisions.</p><div className="flow">INGEST → PROFILE → VALIDATE → REVIEW → VERIFY</div><ul><li>AI explains; it never changes loan data</li><li>Reviewer decisions are revalidated</li><li>SHA-256 integrity and audit history</li></ul></div></section></main>}
function Profile({profile}:any){return <section className="panel"><h2>Ingest & profile</h2><p>{profile?.rows||0} records · {profile?.columns?.length||0} fields</p><table><thead><tr><th>Field</th><th>Missing</th><th>Unique</th></tr></thead><tbody>{profile?.columns?.map((c:any)=><tr key={c.name}><td>{c.name}</td><td>{c.missing}</td><td>{c.unique}</td></tr>)}</tbody></table></section>}
function Queue({overview,exceptions,open}:any){return <section className="panel"><h2>Prioritized reviewer queue</h2><div className="chips">{Object.entries(overview?.exceptions||{}).map(([k,v])=><span className={'chip '+k} key={k}>{k}: {String(v)}</span>)}</div>{exceptions.length?exceptions.map((x:any)=><button className="issue" onClick={()=>open(x)} key={x.id}><span className={'dot '+x.severity}/><b>{x.record.loan_id||'Missing ID'}</b><small>{x.message}</small><em>{x.severity}</em></button>):<p>No open exceptions.</p>}</section>}
function Verification(p:any){return <section className="panel verification"><h2>Final verification status</h2><div className="filters"><label><Search size={15}/><input placeholder="Search Loan ID" value={p.query} onChange={e=>p.setQuery(e.target.value)}/></label><select value={p.status} onChange={e=>p.setStatus(e.target.value)}><option value="">All statuses</option>{['Unreviewed','Needs Review','In Review','Verified','Rejected'].map(x=><option key={x}>{x}</option>)}</select><select value={p.severity} onChange={e=>p.setSeverity(e.target.value)}><option value="">All severities</option>{['critical','high','medium','low'].map(x=><option key={x}>{x}</option>)}</select></div><table><thead><tr><th>Loan ID</th><th>Status</th><th>Open</th><th>Severity</th><th>Source row</th><th/></tr></thead><tbody>{p.rows.map((v:any)=><tr key={v.record_key}><td>{v.loan_id}</td><td><span className={'status '+v.status.replaceAll(' ','-').toLowerCase()}>{v.status}</span></td><td>{v.open_exception_count}</td><td>{v.severities.join(', ')||'—'}</td><td>{v.source_row}</td><td><button className="ghost" onClick={()=>p.history(v.record_key)}><History size={15}/> History</button></td></tr>)}</tbody></table></section>}
function ExceptionDrawer(p:any){const x=p.item,actual=x.actual??x.record[x.field]??'missing';return <div className="drawer"><button className="close" onClick={p.close}>×</button><span className={'chip '+x.severity}>{x.severity}</span><h2>{x.record.loan_id||'Missing ID'}: {x.message}</h2><p><b>Rule:</b> {x.rule}<br/><b>Field:</b> {x.field}<br/><b>Actual:</b> {typeof actual==='object'?JSON.stringify(actual):String(actual)}</p><pre>{JSON.stringify(x.record,null,2)}</pre>{p.role==='reviewer'?<>{!x.ai_explanation?<button onClick={p.assist}><Sparkles size={16}/> Generate AI assistance</button>:<><p className="ai-label">AI ASSISTED — HUMAN REVIEW REQUIRED</p><p>{x.ai_explanation}</p><p>{x.ai_suggestion}</p><button onClick={p.correct}><CheckCircle2 size={16}/> Correct & revalidate</button><button className="ghost" onClick={p.reject}>Reject finding</button></>}</>:<p className="read-only">Read-only governance view. Only an assigned Reviewer can decide.</p>}<button className="ghost" onClick={p.history}><History size={16}/> Record history</button></div>}
function Correction(p:any){const field=p.item.field.split(',')[0].trim();return <div className="modal-backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();p.save()}}><h2>Correction & revalidation</h2><p><b>Loan ID:</b> {p.item.record.loan_id}<br/><b>Correcting field:</b> {field}<br/><b>Reviewer:</b> {currentEmail}</p>{p.item.field.includes(',')&&<p className="read-only">This cross-field rule involves {p.item.field}. Correct the primary field here, then review any remaining related exception.</p>}<label>Corrected value<input required value={p.value} onChange={e=>p.setValue(e.target.value)}/></label><label>Reason<input required minLength={3} value={p.reason} onChange={e=>p.setReason(e.target.value)}/></label><label>Reviewer notes<textarea value={p.notes} onChange={e=>p.setNotes(e.target.value)}/></label><div><button type="button" className="ghost" onClick={p.close}>Cancel</button> <button>Save & Revalidate</button></div></form></div>}
function Admin({users,rules,dataset,close,updateRule,assign}:any){const reviewers=users.filter((u:any)=>u.role==='reviewer'&&u.enabled);return <div className="modal-backdrop"><section className="modal admin-modal"><button className="close" onClick={close}>×</button><h2>Admin Console</h2><h3>Assign selected dataset</h3>{dataset?<select defaultValue="" onChange={e=>e.target.value&&assign(e.target.value)}><option value="">Choose an enabled reviewer</option>{reviewers.map((u:any)=><option key={u.email} value={u.email}>{u.name||u.email} · {u.email}</option>)}</select>:<p>Select a dataset first.</p>}<h3>Users</h3><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Enabled</th></tr></thead><tbody>{users.map((u:any)=><tr key={u.email}><td>{u.name||'—'}</td><td>{u.email}</td><td>{u.role}</td><td>{u.enabled?'Yes':'No'}</td></tr>)}</tbody></table><h3>Validation thresholds</h3>{rules.map((r:any)=><form className="rule-row" key={r.key} onSubmit={e=>{e.preventDefault();updateRule(r,String(new FormData(e.currentTarget).get('value')))}}><label>{r.label}<input name="value" type="number" step="any" defaultValue={r.value}/></label><button>Update</button></form>)}</section></div>}
function Card({title,value}:any){return <div className="card"><small>{title}</small><strong>{value}</strong></div>}
function HistoryModal({data,close}:any){return <div className="modal-backdrop"><section className="modal history"><button className="close" onClick={close}>×</button><h2>{data.loan_id} · {data.status}</h2><p><b>Source:</b> {data.provenance.dataset}, row {data.provenance.source_row}</p><h3>Raw → normalized</h3><pre>{JSON.stringify({raw:data.raw,normalized:data.normalized},null,2)}</pre><h3>SHA-256 integrity</h3><code>{data.record_hash}</code><h3>Correction history</h3>{data.corrections.length?data.corrections.map((c:any,i:number)=><p key={i}><b>{c.reviewer}</b> · {String(c.at)}<br/>{c.changes.map((x:any)=>`${x.field}: ${x.original} → ${x.corrected}`).join(', ')}<br/>Reason: {c.reason}</p>):<p>No corrections recorded.</p>}<h3>Audit history</h3>{data.audit.map((a:any)=><p key={a.id}><b>{a.event}</b><br/><small>{String(a.created_at)} · {a.actor}</small></p>)}</section></div>}
createRoot(document.getElementById('root')!).render(<App/>);
